import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Dashboard from "../components/Dashboard";
import Job from "../components/Job";
import useJobFilterStore from "../store/jobsFilterStore";
import Image from "next/image";

// let allJobsData = [];

export default function Home({ allJobsData }) {
  const [jobsData, setJobsData] = useState([]);
  const jobsFilter = useJobFilterStore((state) => state);

  // useEffect(() => {
  //   getJobsData().then((data) => {
  //     allJobsData = data;
  //     setJobsData(data.slice(0, 10));
  //   });
  // }, []);

  useEffect(() => {
    let filteredData = [...allJobsData];

    if (jobsFilter.company !== "") {
      filteredData = filteredData.filter(({ companyName }) => {
        const regex = new RegExp(jobsFilter.company, "i");
        return regex.test(companyName);
      });
    }
    if (jobsFilter.recent) {
      filteredData.filter((data) => {
        const { postedDate } = data;
        const dayRegex = /(\d+)([dh])/g;

        const match = postedDate.match(dayRegex);

        if (match[1] === "d") {
          return Number(day) <= 7;
        } else {
          return true;
        }
      });
    }

    setJobsData(filteredData.slice(0, 10));
  }, [jobsFilter.company, jobsFilter.recent]);

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Zippia jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard />
        <div className=" grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-28 mt-48 md:mt-44">
          {jobsData.map((jobData) => (
            <Job data={jobData}></Job>
          ))}
        </div>
        <button
          onClick={() =>
            jobsFilter.setIsFilterShowing(!jobsFilter.isFilterShowing)
          }
          className="md:hidden grid place-content-center fixed bottom-2 right-2 p-2 bg-gray-200 rounded-full"
        >
          <Image src="/filterIcon.png" width="48" height="48" />
        </button>
      </main>

      <footer></footer>
    </div>
  );
}

// async function getJobsData() {
//   const requestPayload = {
//     companySkills: true,
//     dismissedListingHashes: [],
//     fetchJobDesc: true,
//     jobTitle: "Business Analyst",
//     locations: [],
//     numJobs: 20,
//     previousListingHashes: [],
//   };
//   const res = await axios.post(
//     "https://www.zippia.com/api/jobs/",
//     requestPayload
//   );
//   return res.data.jobs;
// }

export async function getStaticProps(context) {
  const requestPayload = {
    companySkills: true,
    dismissedListingHashes: [],
    fetchJobDesc: true,
    jobTitle: "Business Analyst",
    locations: [],
    numJobs: 20,
    previousListingHashes: [],
  };
  const res = await axios.post(
    "https://www.zippia.com/api/jobs/",
    requestPayload
  );

  if (!res.data) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { allJobsData: res.data.jobs }, // will be passed to the page component as props
  };
}
